'use client';

import { useDataStore, useEnsureDetail, useViewStore } from '@/lib/store';
import { UTILITY_LABEL } from '@/lib/cesium/materials';
import { levelLabel, parentOf } from '@/lib/ulpin';
import type { AssetType, Provenance, UtilityProps } from '@/lib/types';
import UlpinCard from './UlpinCard';
import { DERIVED_PARCEL_NOTE, ProvenanceRow } from './Provenance';

/**
 * One panel, four modes: property / floor / unit / utility.
 *
 * Every mode ends in a provenance row. That is a hard rule rather than a
 * nicety: a viewer must never be left unsure whether a number in front of them
 * was surveyed or guessed.
 */

function Row({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex items-baseline justify-between gap-3 py-[3px]">
      <span className="row-label shrink-0">{label}</span>
      <span className="row-value text-right">{value}</span>
    </div>
  );
}

const m2 = (v: number) => `${v.toLocaleString(undefined, { maximumFractionDigits: 1 })} m²`;
const m = (v: number) => `${v.toFixed(1)} m`;

export default function DetailPanel() {
  const mode = useViewStore((s) => s.mode);
  const activeBuildingId = useViewStore((s) => s.activeBuildingId);
  const isolatedFloor = useViewStore((s) => s.isolatedFloor);
  const selectedUnitId = useViewStore((s) => s.selectedUnitId);
  const selectedUtilityId = useViewStore((s) => s.selectedUtilityId);
  const underground = useViewStore((s) => s.underground);

  const buildings = useDataStore((s) => s.buildings);
  const utilities = useDataStore((s) => s.utilities);
  const conflicts = useDataStore((s) => s.conflicts);
  const detail = useEnsureDetail(activeBuildingId);

  // ---- utility -----------------------------------------------------------
  if (selectedUtilityId !== null) {
    const feat = utilities?.features.find((f) => f.properties.id === selectedUtilityId);
    const u = feat?.properties as UtilityProps | undefined;
    if (u) {
      const related = conflicts.filter((c) => c.utility_id === u.id);
      return (
        <Panel title={UTILITY_LABEL[u.asset_type as AssetType]} kicker="Utility asset">
          <Row label="Asset ID" value={<span className="font-mono">#{u.id}</span>} />
          <Row label="Type" value={UTILITY_LABEL[u.asset_type as AssetType]} />
          <Row label="Depth" value={`${u.depth_m.toFixed(1)} m below datum`} />
          <Row label="Corridor radius" value={m(u.radius_m)} />
          <Row label="Authority" value={u.authority} />
          <Row
            label="Status"
            value={
              <span className={u.status === 'operational' ? '' : 'text-red-400'}>
                {u.status}
              </span>
            }
          />
          {related.length > 0 ? (
            <div className="mt-2 rounded border border-red-500/40 bg-red-500/10 p-2">
              <div className="text-[11px] font-semibold text-red-300">
                {related.length} basement conflict{related.length > 1 ? 's' : ''}
              </div>
              {related.map((c) => (
                <div key={c.id} className="mt-1 font-mono text-[10px] text-red-200/90">
                  {c.building_ulpin} · level {c.level_no}
                </div>
              ))}
            </div>
          ) : null}
          <ProvenanceRow
            source={'estimated'}
            note={
              'Alignment generated by offsetting OSM road centrelines. '
              + 'Representative of a service corridor, not an as-built utility record.'
            }
          />
        </Panel>
      );
    }
  }

  const bprops = buildings?.features.find(
    (f) => f.properties.id === activeBuildingId,
  )?.properties;

  // ---- nothing selected --------------------------------------------------
  // In underground mode with no corridor picked, the surface stack is not the
  // subject any more -- showing the previously selected unit here would be
  // stale context, so fall back to the area summary.
  if (!bprops || mode === 'city' || (underground && selectedUtilityId === null)) {
    return (
      <Panel title="Siripuram, Visakhapatnam" kicker="Area of interest">
        <Row label="Buildings" value={buildings?.features.length ?? '—'} />
        <Row label="Utility runs" value={utilities?.features.length ?? '—'} />
        <Row label="Flagged conflicts" value={conflicts.length} />
        <Row label="CRS" value="EPSG:4326 · Z in metres" />
        <p className="mt-3 text-[11px] leading-snug text-[rgb(var(--muted))]">
          {underground
            ? 'Underground view. Click a utility corridor to inspect it.'
            : 'Click any building to open its vertical stack.'}
        </p>
      </Panel>
    );
  }

  const synthetic = Boolean(
    (bprops as unknown as { survey_synthetic?: boolean }).survey_synthetic,
  );

  // ---- unit --------------------------------------------------------------
  if (selectedUnitId !== null && detail) {
    const unit = detail.units.find((x) => x.id === selectedUnitId);
    const floor = detail.floors.find((f) => f.id === unit?.floor_id);
    if (unit) {
      const height = unit.z_max - unit.z_min;
      return (
        <Panel title={`Unit ${unit.unit_no}`} kicker="Titled unit">
          <UlpinCard ulpin={unit.ulpin} />
          <div className="mt-2">
            <Row label="Level" value={levelLabel(unit.level_no, bprops.floors - 1)} />
            <Row label="Carpet area" value={m2(unit.carpet_m2)} />
            <Row label="Built-up area" value={m2(unit.built_m2)} />
            <Row label="Volume" value={`${(unit.built_m2 * height).toFixed(0)} m³`} />
            <Row
              label="Z extent"
              value={`${unit.z_min.toFixed(2)} → ${unit.z_max.toFixed(2)} m`}
            />
            <Row label="Clear height" value={m(height)} />
            <Row label="Tenure" value={unit.tenure} />
            <Row
              label="Encumbrance"
              value={
                <span className={unit.encumbrance === 'None' ? '' : 'text-amber-300'}>
                  {unit.encumbrance}
                </span>
              }
            />
            <Row
              label="Parent parcel"
              value={
                <span className="font-mono text-[11px]">
                  {detail.parcel?.ulpin ?? parentOf(unit.ulpin) ?? '—'}
                </span>
              }
            />
            <Row label="Registered owner" value={detail.parcel?.owner ?? '—'} />
          </div>
          <ProvenanceRow
            source={(floor?.detect_source ?? bprops.height_source) as Provenance}
            synthetic={synthetic}
            note={
              'Unit boundaries are a grid subdivision of the building footprint, '
              + 'not a registered floor plan. Tenure and encumbrance are synthetic.'
            }
          />
        </Panel>
      );
    }
  }

  // ---- floor -------------------------------------------------------------
  if (isolatedFloor !== null && detail) {
    const floor = detail.floors.find((f) => f.level_no === isolatedFloor);
    if (floor) {
      const units = detail.units.filter((u) => u.level_no === isolatedFloor);
      const gross = units.reduce((a, u) => a + u.built_m2, 0);
      return (
        <Panel
          title={`Level ${levelLabel(floor.level_no, bprops.floors - 1)}`}
          kicker={floor.level_no < 0 ? 'Basement level' : 'Floor level'}
        >
          <UlpinCard ulpin={floor.ulpin} />
          <div className="mt-2">
            <Row label="Level number" value={floor.level_no} />
            <Row
              label="Z extent"
              value={`${floor.z_min.toFixed(2)} → ${floor.z_max.toFixed(2)} m`}
            />
            <Row label="Slab height" value={m(floor.z_max - floor.z_min)} />
            <Row label="Units on level" value={units.length || '— (non-habitable)'} />
            {gross > 0 ? <Row label="Total built-up" value={m2(gross)} /> : null}
            <Row
              label="Parent building"
              value={<span className="font-mono text-[11px]">{bprops.ulpin}</span>}
            />
          </div>
          <ProvenanceRow source={floor.detect_source} synthetic={synthetic} />
        </Panel>
      );
    }
  }

  // ---- building ----------------------------------------------------------
  const totalUnits = detail?.units.length ?? 0;
  return (
    <Panel
      title={bprops.name ?? `${bprops.use_type} building`}
      kicker="Building"
    >
      <UlpinCard ulpin={bprops.ulpin} />
      <div className="mt-2">
        <Row label="Use type" value={<span className="capitalize">{bprops.use_type}</span>} />
        {bprops.address ? <Row label="Address" value={bprops.address} /> : null}
        <Row label="Height" value={m(bprops.height_m)} />
        <Row label="Storeys" value={`${bprops.floors} above ground`} />
        <Row label="Basements" value={bprops.basements} />
        <Row label="Ground elevation" value={m(bprops.ground_elev)} />
        <Row label="Units" value={totalUnits || '—'} />
        <Row
          label="Parent parcel"
          value={
            <span className="font-mono text-[11px]">{detail?.parcel?.ulpin ?? '—'}</span>
          }
        />
        <Row label="Registered owner" value={detail?.parcel?.owner ?? '—'} />
        {detail?.parcel ? (
          <Row label="Parcel area" value={m2(detail.parcel.area_m2)} />
        ) : null}
      </div>
      <ProvenanceRow source={bprops.height_source} synthetic={synthetic} />
      <p className="mt-2 text-[9px] leading-snug text-[rgb(var(--muted))]">
        {DERIVED_PARCEL_NOTE} Owner names are synthetic placeholders.
      </p>
    </Panel>
  );
}

function Panel({
  title,
  kicker,
  children,
}: {
  title: string;
  kicker: string;
  children: React.ReactNode;
}) {
  return (
    <div className="glass rounded-lg p-3">
      <div className="panel-title">{kicker}</div>
      <h2 className="mt-0.5 truncate text-[15px] font-semibold capitalize text-[rgb(var(--ink))]">
        {title}
      </h2>
      <div className="mt-2">{children}</div>
    </div>
  );
}
