/**
 * ULPIN round-trip tests.
 *
 * Run with:  node --test lib/ulpin.test.ts
 * (Node strips the type annotations natively; there is no build step.)
 *
 * These also pin the encoding that db/02_functions.sql's ulpin_fmt() mirrors --
 * if the two ever diverge, identifiers generated by the pipeline stop parsing
 * in the UI, so the format is asserted literally rather than by construction.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { generate, parse, levelOf, parentOf, floorCode, parseFloorCode } from './ulpin.ts';

test('generates right-truncated identifiers at each level', () => {
  assert.equal(generate(42), 'AP-VSP-3D26-0042');
  assert.equal(generate(42, 7), 'AP-VSP-3D26-0042-007');
  assert.equal(generate(42, 7, 0), 'AP-VSP-3D26-0042-007-00');
  assert.equal(generate(42, 7, 5), 'AP-VSP-3D26-0042-007-05');
  assert.equal(generate(42, 7, -2), 'AP-VSP-3D26-0042-007-B2');
  assert.equal(generate(42, 7, 5, 3), 'AP-VSP-3D26-0042-007-05-03');
});

test('matches the SQL encoding for the cases ulpin_fmt covers', () => {
  // Fixed expectations, verified against a live postgres ulpin_fmt() call.
  assert.equal(generate(42), 'AP-VSP-3D26-0042');
  assert.equal(generate(42, 7), 'AP-VSP-3D26-0042-007');
  assert.equal(generate(42, 7, 0), 'AP-VSP-3D26-0042-007-00');
  assert.equal(generate(42, 7, -2), 'AP-VSP-3D26-0042-007-B2');
  assert.equal(generate(42, 7, 5, 3), 'AP-VSP-3D26-0042-007-05-03');
});

test('round-trips through parse at every level', () => {
  const cases: [number, number?, number?, number?][] = [
    [1], [325], [42, 7], [42, 7, 0], [42, 7, 12], [42, 7, -1], [42, 7, -2, 4],
    [9999, 999, 99, 99],
  ];
  for (const [p, b, f, u] of cases) {
    const id = generate(p, b, f, u);
    const back = parse(id);
    assert.ok(back, `failed to parse ${id}`);
    assert.equal(back.parcel, p);
    assert.equal(back.building, b);
    assert.equal(back.floor, f);
    assert.equal(back.unit, u);
    assert.equal(generate(back.parcel, back.building, back.floor, back.unit), id);
  }
});

test('floor codes survive a round trip, basements included', () => {
  for (const level of [-9, -2, -1, 0, 1, 9, 12, 99]) {
    assert.equal(parseFloorCode(floorCode(level)), level);
  }
  assert.equal(floorCode(0), '00');
  assert.equal(floorCode(-1), 'B1');
  assert.equal(floorCode(7), '07');
});

test('reports the addressed level', () => {
  assert.equal(levelOf(generate(1)), 'parcel');
  assert.equal(levelOf(generate(1, 2)), 'building');
  assert.equal(levelOf(generate(1, 2, 3)), 'floor');
  assert.equal(levelOf(generate(1, 2, 3, 4)), 'unit');
});

test('walks up the hierarchy', () => {
  const unit = generate(42, 7, 5, 3);
  assert.equal(parentOf(unit), 'AP-VSP-3D26-0042-007-05');
  assert.equal(parentOf(parentOf(unit)!), 'AP-VSP-3D26-0042-007');
  assert.equal(parentOf(parentOf(parentOf(unit)!)!), 'AP-VSP-3D26-0042');
  assert.equal(parentOf(generate(42)), null);
});

test('rejects identifiers that are not ours', () => {
  for (const bad of [
    '', 'not-a-ulpin', 'AP-VSP-3D26', 'AP-VSP-3D26-42', 'AP-VSP-3D26-0042-7',
    'XX-VSP-3D26-0042', 'AP-VSP-3D26-0042-007-5', 'AP-VSP-3D26-0042-007-05-3',
    'AP-VSP-3D26-0042-007-XX',
  ]) {
    assert.equal(parse(bad), null, `should have rejected ${JSON.stringify(bad)}`);
  }
});

test('accepts lower case and surrounding whitespace', () => {
  assert.deepEqual(parse('  ap-vsp-3d26-0042-007-b2  '), {
    parcel: 42, building: 7, floor: -2,
  });
});
