/**
 * ULPIN round-trip tests.
 *
 * Run with:  node --test lib/ulpin.test.ts
 * (Node strips the type annotations natively; there is no build step.)
 *
 * These also pin the encoding that db/02_functions.sql's ulpin_fmt() mirrors --
 * if the two ever diverge, identifiers generated by the pipeline stop parsing
 * in the UI, so the format is asserted literally rather than by construction.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {
  codesOf, floorCode, generate, levelOf, parentOf, parse, parseFloorCode,
  prefixFor, DEFAULT_CODES,
} from './ulpin.ts';

/** A second project, in a different state and district. */
const TS_HYD = { state: 'TS', district: 'HYD', scheme: '3D26' };

test('generates right-truncated identifiers at each level', () => {
  assert.equal(generate(42), 'AP-VSP-3D26-0042');
  assert.equal(generate(42, 7), 'AP-VSP-3D26-0042-007');
  assert.equal(generate(42, 7, 0), 'AP-VSP-3D26-0042-007-00');
  assert.equal(generate(42, 7, 5), 'AP-VSP-3D26-0042-007-05');
  assert.equal(generate(42, 7, -2), 'AP-VSP-3D26-0042-007-B2');
  assert.equal(generate(42, 7, 5, 3), 'AP-VSP-3D26-0042-007-05-03');
});

test('matches the SQL encoding for the cases ulpin_fmt covers', () => {
  // Fixed expectations, verified against a live postgres ulpin_fmt() call.
  assert.equal(generate(42), 'AP-VSP-3D26-0042');
  assert.equal(generate(42, 7), 'AP-VSP-3D26-0042-007');
  assert.equal(generate(42, 7, 0), 'AP-VSP-3D26-0042-007-00');
  assert.equal(generate(42, 7, -2), 'AP-VSP-3D26-0042-007-B2');
  assert.equal(generate(42, 7, 5, 3), 'AP-VSP-3D26-0042-007-05-03');
});

/**
 * The same parity assertion for a SECOND project.
 *
 * ulpin_fmt() gained three code arguments so that a project outside
 * Visakhapatnam mints identifiers in its own state and district. The two
 * implementations have to agree for those too, or an identifier generated by
 * the pipeline stops parsing in the UI -- which is the whole reason this file
 * asserts the format literally rather than by construction.
 *
 * Fixed expectations, verified against:
 *   SELECT ulpin_fmt(42, 7, 5, 3, 'TS', 'HYD', '3D26');
 */
test('matches the SQL encoding for a second project (TS/HYD)', () => {
  assert.equal(generate(42, undefined, undefined, undefined, TS_HYD),
    'TS-HYD-3D26-0042');
  assert.equal(generate(42, 7, undefined, undefined, TS_HYD),
    'TS-HYD-3D26-0042-007');
  assert.equal(generate(42, 7, 0, undefined, TS_HYD), 'TS-HYD-3D26-0042-007-00');
  assert.equal(generate(42, 7, -2, undefined, TS_HYD), 'TS-HYD-3D26-0042-007-B2');
  assert.equal(generate(42, 7, 5, 3, TS_HYD), 'TS-HYD-3D26-0042-007-05-03');
});

/**
 * The defaults are what make this change invisible to the demo project.
 *
 * Every ULPIN in data/api/siripuram/ was minted before ulpin_fmt() and
 * generate() took codes at all. If a code-less call ever stopped producing
 * the AP-VSP-3D26 prefix, 384 buildings, 325 parcels, 1,810 floors and 6,438
 * units would all change identifier at once.
 */
test('omitting the codes still mints the demo project prefix', () => {
  assert.deepEqual(DEFAULT_CODES, { state: 'AP', district: 'VSP', scheme: '3D26' });
  assert.equal(prefixFor(), 'AP-VSP-3D26');
  assert.equal(prefixFor(TS_HYD), 'TS-HYD-3D26');
  for (const args of [[1], [325], [42, 7], [42, 7, 0], [42, 7, -1], [42, 7, 5, 3]]) {
    const [p, b, f, u] = args as [number, number?, number?, number?];
    assert.ok(generate(p, b, f, u).startsWith('AP-VSP-3D26-'));
    assert.equal(generate(p, b, f, u), generate(p, b, f, u, DEFAULT_CODES));
  }
});

test('parcel numbering restarts per project; the prefix keeps them apart', () => {
  // Parcel 0001 exists in both projects, which is the point -- it is the
  // state/district prefix that makes the two identifiers different.
  const ap = generate(1, 1, 0, 1);
  const ts = generate(1, 1, 0, 1, TS_HYD);
  assert.notEqual(ap, ts);
  assert.deepEqual(parse(ap), parse(ts, TS_HYD));
  assert.deepEqual(codesOf(ap), DEFAULT_CODES);
  assert.deepEqual(codesOf(ts), TS_HYD);
});

test('a second project round-trips at every level', () => {
  const cases: [number, number?, number?, number?][] = [
    [1], [325], [42, 7], [42, 7, 0], [42, 7, 12], [42, 7, -1], [42, 7, -2, 4],
    [9999, 999, 99, 99],
  ];
  for (const [p, b, f, u] of cases) {
    const id = generate(p, b, f, u, TS_HYD);
    const back = parse(id, TS_HYD);
    assert.ok(back, `failed to parse ${id}`);
    assert.equal(back.parcel, p);
    assert.equal(back.building, b);
    assert.equal(back.floor, f);
    assert.equal(back.unit, u);
    assert.equal(generate(back.parcel, back.building, back.floor, back.unit, TS_HYD), id);
    // Walking up must not silently relabel the identifier as AP-VSP.
    const up = parentOf(id);
    if (up !== null) assert.ok(up.startsWith('TS-HYD-3D26-'), up);
  }
});

test('a strict parse rejects the codes of another project', () => {
  // The default is the demo project's codes, so this still rejects exactly
  // what it always rejected -- including XX-VSP below.
  assert.equal(parse('TS-HYD-3D26-0042'), null);
  assert.equal(parse('AP-VSP-3D26-0042', TS_HYD), null);
  // 'any' accepts whatever well-formed prefix it finds, which is what a
  // viewer already showing a project's data needs.
  assert.deepEqual(parse('TS-HYD-3D26-0042', 'any'), { parcel: 42 });
  assert.equal(levelOf('TS-HYD-3D26-0042-007-05-03'), 'unit');
  // Shape still has to hold, whatever the codes.
  assert.equal(parse('T-HYD-3D26-0042', 'any'), null);
  assert.equal(parse('TS-HYD-3D26-42', 'any'), null);
  assert.equal(codesOf('not-a-ulpin'), null);
});

test('round-trips through parse at every level', () => {
  const cases: [number, number?, number?, number?][] = [
    [1], [325], [42, 7], [42, 7, 0], [42, 7, 12], [42, 7, -1], [42, 7, -2, 4],
    [9999, 999, 99, 99],
  ];
  for (const [p, b, f, u] of cases) {
    const id = generate(p, b, f, u);
    const back = parse(id);
    assert.ok(back, `failed to parse ${id}`);
    assert.equal(back.parcel, p);
    assert.equal(back.building, b);
    assert.equal(back.floor, f);
    assert.equal(back.unit, u);
    assert.equal(generate(back.parcel, back.building, back.floor, back.unit), id);
  }
});

test('floor codes survive a round trip, basements included', () => {
  for (const level of [-9, -2, -1, 0, 1, 9, 12, 99]) {
    assert.equal(parseFloorCode(floorCode(level)), level);
  }
  assert.equal(floorCode(0), '00');
  assert.equal(floorCode(-1), 'B1');
  assert.equal(floorCode(7), '07');
});

test('reports the addressed level', () => {
  assert.equal(levelOf(generate(1)), 'parcel');
  assert.equal(levelOf(generate(1, 2)), 'building');
  assert.equal(levelOf(generate(1, 2, 3)), 'floor');
  assert.equal(levelOf(generate(1, 2, 3, 4)), 'unit');
});

test('walks up the hierarchy', () => {
  const unit = generate(42, 7, 5, 3);
  assert.equal(parentOf(unit), 'AP-VSP-3D26-0042-007-05');
  assert.equal(parentOf(parentOf(unit)!), 'AP-VSP-3D26-0042-007');
  assert.equal(parentOf(parentOf(parentOf(unit)!)!), 'AP-VSP-3D26-0042');
  assert.equal(parentOf(generate(42)), null);
});

test('rejects identifiers that are not ours', () => {
  for (const bad of [
    '', 'not-a-ulpin', 'AP-VSP-3D26', 'AP-VSP-3D26-42', 'AP-VSP-3D26-0042-7',
    'XX-VSP-3D26-0042', 'AP-VSP-3D26-0042-007-5', 'AP-VSP-3D26-0042-007-05-3',
    'AP-VSP-3D26-0042-007-XX',
  ]) {
    assert.equal(parse(bad), null, `should have rejected ${JSON.stringify(bad)}`);
  }
});

test('accepts lower case and surrounding whitespace', () => {
  assert.deepEqual(parse('  ap-vsp-3d26-0042-007-b2  '), {
    parcel: 42, building: 7, floor: -2,
  });
});
